name: build-kylin-rpm

on: workflow_dispatch          # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest      # GitHub 提供 x86_64  runner
    container: 
      image: kylinos/kylin:v10-sp3-x86_64   # 官方麒麟容器
      options: --user root
    steps:
      - name: install dnf-utils
        run: |
          dnf install -y 'dnf-command(download)' yum-utils
      - name: download mosquitto + deps
        run: |
          mkdir /rpm && cd /rpm
          dnf download --resolve mosquitto
      - name: pack
        run: |
          cd /rpm
          tar czf mosquitto-kylin10-x86_64.tar.gz *.rpm
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: mosquitto-kylin10-x86_64
          path: /rpm/mosquitto-kylin10-x86_64.tar.gz
