name: build-kylin-arm64-rpm

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
      options: --user root --platform linux/arm64/v8
    steps:
      # ① 创建 Rocky 9 默认源（最小镜像可能为空）
      - name: create default repos
        run: |
          cat >/etc/yum.repos.d/rocky.repo <<'EOF'
          [baseos]
          name=Rocky Linux 9 - BaseOS
          baseurl=http://dl.rockylinux.org/vault/rocky/9/BaseOS/$basearch/os/
          enabled=1
          gpgcheck=0
          [appstream]
          name=Rocky Linux 9 - AppStream
          baseurl=http://dl.rockylinux.org/vault/rocky/9/AppStream/$basearch/os/
          enabled=1
          gpgcheck=0
          [crb]
          name=Rocky Linux 9 - CRB
          baseurl=http://dl.rockylinux.org/vault/rocky/9/CRB/$basearch/os/
          enabled=1
          gpgcheck=0
          EOF

      # ② 启用 EPEL
      - name: enable epel
        run: |
          dnf install -y epel-release

      # ③ 安装下载器
      - name: install utils
        run: dnf install -y 'dnf-command(download)'

      # ④ 抓包（含依赖）
      - name: download mosquitto
        run: |
          mkdir /rpm && cd /rpm
          dnf download --resolve mosquitto

      # ⑤ 打包 & 上传
      - name: pack
        run: |
          cd /rpm
          tar czf mosquitto-kylin10-aarch64.tar.gz *.rpm

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: mosquitto-kylin10-aarch64
          path: /rpm/mosquitto-kylin10-aarch64.tar.gz
